version: '3.8'

services:

    database_clientes: 
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: 'root'
           MYSQL_DATABASE: 'builders'
           MYSQL_USER: 'geraldo'
           MYSQL_PASSWORD: 'odlareg' 
        ports:
        - '3306:3306'
        expose:
        - '3306'
        volumes:
        - mysqldata:/var/lib/mysql
        
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped   

    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped 

networks:
    nesjs-network:
volumes:
    mysqldata:
      driver: local
  
