version: '3.8'

services:
    database_clientes: 
        image: mysql
        container_name: database_clientes
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: builders
            MYSQL_USER: geraldo
            MYSQL_PASSWORD: odlareg 
        volumes:
            - mysqldata:/var/lib/mysql
            - ./.database/:/docker-entrypoint-initdb.d/
        networks:
          - nesjs-network
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 8080:3333
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        links:
          - database_clientes
        depends_on:
          - database_clientes
          
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 8080:3333
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
networks:
    nesjs-network:
volumes:
    mysqldata:
      driver: local
  
